# Generated by Django 6.0.5 on 2026-06-28 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='event',
            new_name='events_even_title_aedf91_idx',
            old_name='events_even_title_5ac707_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='events_even_is_recu_7dd095_idx',
            old_name='events_even_is_recu_2f4984_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='events_even_created_7af6de_idx',
            old_name='events_even_created_132f61_idx',
        ),
    ]
