# Generated by Django 6.0.5 on 2026-09-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('cover_image_url', models.URLField()),
                ('cover_image_alt_text', models.CharField(max_length=255)),
                ('external_url', models.URLField()),
            ],
            options={
                'verbose_name': 'Basic Event',
                'verbose_name_plural': 'Basic Events',
            },
        ),
        migrations.CreateModel(
            name='BibleReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Bible Reference',
                'verbose_name_plural': 'Bible References',
            },
        ),
        migrations.CreateModel(
            name='HeroGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('alt_text', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Hero Gallery',
                'verbose_name_plural': 'Hero Galleries',
            },
        ),
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('alt_text', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Hero Image',
                'verbose_name_plural': 'Hero Images',
            },
        ),
        migrations.CreateModel(
            name='LastestSermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('cover_image_url', models.URLField()),
                ('cover_image_alt_text', models.CharField(max_length=255)),
                ('preacher', models.CharField(max_length=255)),
                ('tags', models.CharField(max_length=255)),
                ('external_url', models.URLField()),
            ],
            options={
                'verbose_name': 'Lastest Sermon',
                'verbose_name_plural': 'Lastest Sermons',
            },
        ),
        migrations.CreateModel(
            name='WelcomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image_url', models.URLField()),
                ('image_alt_text', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Welcome Content',
                'verbose_name_plural': 'Welcome Contents',
            },
        ),
    ]
