# Generated by Django 6.0.5 on 2026-09-05 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
                ('image_alt_text', models.CharField(max_length=255)),
                ('mission', models.TextField()),
                ('vision', models.TextField()),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'Abouts',
            },
        ),
    ]
